# Generated by Django 4.0.2 on 2022-04-22 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_certificaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregable',
            name='nota',
            field=models.IntegerField(default=0),
        ),
    ]
