# Generated by Django 4.0.4 on 2022-05-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_entregable_nota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('grupo', models.IntegerField()),
                ('repeticiones_semanales', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlanPersonalizable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('fechaDeInicio', models.DateField()),
                ('asignado', models.BooleanField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Profesor',
            new_name='PersonalTrainer',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Entregable',
        ),
        migrations.AlterModelOptions(
            name='certificaciones',
            options={'verbose_name': 'Certificaciones', 'verbose_name_plural': 'Certificaciones'},
        ),
        migrations.AlterModelOptions(
            name='personaltrainer',
            options={'verbose_name': 'PersonalTrainer', 'verbose_name_plural': 'Entrenadores Personales'},
        ),
    ]
